###
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "author": "Ali Omar",
    "title": "My second blog post",
    "url": "https://myfirsturl.com",
    "likes": 43
}